server:
  port: 8080
  servlet:
    context-path: /api/msclientes


spring:
  mvc:
    throw-exception-if-no-handler-found: true
    web:
      resources:
        add-mappings: false
  application:
    name: msclientes
  datasource:
    url: jdbc:mysql://localhost:3306/msclientes?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: 2112
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

